#Project Euler, Problem 44
#Pentagon numbers

"""Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. 
The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P4 + P7 = 22 + 70 = 92 = P8. 
However, their difference, 70 − 22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, Pj and Pk, 
for which their sum and difference are pentagonal 
and D = |Pk − Pj| is minimised; what is the value of D?
"""

import time

def isitpentagonal(n):
    if (((1+24*n)**0.5)+1)/6 % 1 == 0:
        return True
    return False

def sumdif():
    found = True
    i = 1
    while found:
        for j in range(1000,i):
            a = i*(3*i-1)/2
            b = j*(3*j-1)/2
            if isitpentagonal(a+b) and isitpentagonal(a-b):
                return int(a-b)
        i += 1

start = time.time()
print(sumdif())
print(time.time() - start)
#5482660 in 0.45378708839416504 secs